language: python
python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
install:
  - pip install tox coveralls
script:
  - export TOX_ENV=`echo $TRAVIS_PYTHON_VERSION | sed -E 's/^([0-9])\.([0-9])$/py\1\2/'`
  - tox -e $TOX_ENV
before_install:
  - sudo apt-get install -y graphviz
after_success:
  - coveralls

